# Generated deployment configuration for Enhanced eCommerce Store
# Namespace: ${namespace}
# Generated by Terraform

apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ${namespace}
data:
  app_name: "enhanced-ecommerce-store"
  environment: "production"
  product_service_port: "${product_service_port}"
  order_service_port: "${order_service_port}"
  frontend_port: "${frontend_port}"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-external
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
  - port: ${product_service_port}
    targetPort: ${product_service_port}
    nodePort: 30011
  selector:
    app: product-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-external
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
  - port: ${order_service_port}
    targetPort: ${order_service_port}
    nodePort: 30012
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
  - port: ${frontend_port}
    targetPort: ${frontend_port}
    nodePort: 30010
  selector:
    app: frontend
